### ISSUE TITLE
Route namespace issue

### ISSUE THREAD

**Issue by timurvafin** [ianwhite/pickle#18]
Hey,

Got some issue related to namespaces in the routing.

For example we have in the routes.rb articles resource namespaced with admin

``` ruby
namespace :admin do
  resources :articles
end
```

Then admin_article_path, admin_articles_path and other named routes will be available.
If we will try to write route step generated y pickle like

``` cucumber
Given I am on the admin article's page
```

it will execute `path_to_pickle 'the admin', 'article'` and tries to find instance of the Admin model with the "admin" ref.

So in case we have "the admin" in current scenario it will try to run `admin_articles_path(admin_instance, article_instance)`

Not sure how to solve this case, probably the best way is to have `:namespace` option for `path_to_pickle` method.

What do you think?

**Comment by mathieujobin** [comment]
6 years old,.. you must have figure this one out by now ...
