### ISSUE TITLE
ActiveResource model factories and Pickle not working

### ISSUE THREAD

**Issue by joshnabbott** [ianwhite/pickle#27]
I just started using Pickle and I'm loving the steps it provides me with! I have on ActiveRecord model that is working just fine, but apparently using an ActiveResource model isn't working properly with Pickle.

In short, I tried writing:

Given the following accounts exist:
| name    |
| Joshua |

And Cucumber gives me an unimplemented step warning.

I'm using Rails 3 and Machinist2 to create factories and when I run the debugger, I am able to run Account.make just fine, but when I output:

Pickle.config.factories

It doesn't return any of the factories inheriting from ActiveResource.

I'm guessing this may be fixable with an adapter? Is there something out there that can give me the functionality I'm looking for?

I really appreciate your help!

Thanks,
-- Josh

**Comment by mathieujobin** [comment]
6 years old,.. you must have figure this one out by now ...
