### ISSUE TITLE
rails destroy pickle deletes all features contents

### ISSUE THREAD

**Issue by kalabiyau** [ianwhite/pickle#34]
```
rails destroy pickle   
      remove  features/step_definitions
      remove  features/support
      remove  features/step_definitions/pickle_steps.rb
      remove  features/support/pickle.rb
```

But we assume that support/ or step_definitions/ can have some useful stuff like env.rb or cuke stepdefs

**Comment by mathieujobin** [comment]
please open a pull request if you know how to improve this task.
otherwise, people should be using git and have a look at what they delete before commiting... 

closing
