### ISSUE TITLE
could this gem work without the generator?

### ISSUE THREAD

**Issue by mathieujobin** [ianwhite/pickle#64]
Hello, I am opening this for discussion:

I wonder if anyone ever had the plan to make this gem works simply by including it in the gemfile.

steps and all would be included automatically.
and upgrades would be done via bundle

I dont like the idea of copying steps into my app anymore..

**Comment by chewi** [comment]
Comparing my pickle_steps.rb with the stock one, I only made one minor change to make the create_model step case-insensitive so you do have a point. We are still using this but not enough to plough much more time into it. If this were to be done, I would want it to be possible to override the stock file.

**Comment by josephks** [comment]
:+1: I would make the user specifically include a file with step defs rather than just have them defined when the gem is loaded.

**Comment by mathieujobin** [comment]
I really think it should.. but I don't know if I will work on making this change I have suggested.

closing
