### ISSUE TITLE
Fields with arrays

### ISSUE THREAD

**Issue by thessem** [ianwhite/pickle#65]
Is it possible to achieve the following without having to write my own custom step:
```
Given a company "test" exists with company_name: "Test Company"
Given a user exists with companies: [company "test"]
```
Where the field companies requires an array of companies. In this example I only need a single element

Alternatively, is there a elegant way to write this as a custom step?

**Comment by chewi** [comment]
This looks like a HABTM. I don't think there's currently a way to do that. Modifying Pickle to do this might not be that hard but I'm afraid you'll have to do it yourself!
