### ISSUE TITLE
use Module#prepend instead of alias_method_chain

### ISSUE THREAD

**Issue by mathieujobin** [ianwhite/pickle#69]
this will be required for Rails 5.1
and is quite the deprecation annoyance on 5.0

**Comment by mathieujobin** [comment]
I made this draft, https://github.com/venuenext/pickle/commit/a44b11fdd0e1324d9a4d9adea621e2c54d61b491

but its hard to test with a broken test suite build on top of ruby 3.x

is there a community of people interested to see pickle ported to rails 5.x ? 
or should we be looking at alternatives?

**Comment by mathieujobin** [comment]
and this one https://github.com/venuenext/pickle/commit/f0393413ab07bee6641da293fcf8ca2369eac967

**Comment by mikaelhm** [comment]
Your draft is working fine for me.

**Comment by mathieujobin** [comment]
I opened this pull request, we are using this branch everywhere now

https://github.com/ianwhite/pickle/pull/70

**Comment by mathieujobin** [comment]
done and merged, v0.5.2
