### ISSUE TITLE
create model with different factory name

### ISSUE THREAD

**Issue by lemingos** [ianwhite/pickle#73]
Is it possible to create model with different factory name?  I would like to have definition like:

```
Given student exists as user
```
which would create model('user') with factory :student

That would let me reuse code I already have.

**Comment by chewi** [comment]
I'm a bit rusty on the internals. I don't think you can do that but you can give models arbitrary names.

```
Given a student "foo" exists
model('student: "foo"')
```

**Comment by lemingos** [comment]
Unfortunately that's not much help :/ 
Maybe I could rename model('x') to model('y') somehow?

**Comment by chewi** [comment]
Looking at the source, it stores the record under both the factory name and the model name and if you don't qualify which user you want then the `model` method will just give you the last record. Try it and see.

```
Given a student exists
model('user')
```

**Comment by lemingos** [comment]
That worked great! Thank you for help.
