### ISSUE TITLE
This repo is still supported?

### ISSUE THREAD

**Issue by suchov** [ianwhite/pickle#74]
I see 7 issues in the repo + 7 PR that a pretty old. Thinking about adding this gem to my work project & not sure if it's still maintaining.

**Comment by chewi** [comment]
You should have seen how many there were before I fixed it up. It more or less still works so no has cared enough to get commit access and do another release. There are some annoying warnings with Rails 5 but I won't get time to look at that fix until we start using Rails 5 ourselves.

**Comment by suchov** [comment]
Thanks a ton for so quick response! @chewi That's great, thank you for your effort!
